GET http://localhost/api/v1/users/me
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2FwaS92MS9hdXRoL2xvZ2luIiwiaWF0IjoxNjk5NTI1NDQyLCJleHAiOjE2OTk1MjkwNDIsIm5iZiI6MTY5OTUyNTQ0MiwianRpIjoiN0N6Zm4xaDVXUElNUnZSZSIsInN1YiI6IjlhOTIyODJmLTExMTAtNDM4ZS1iYWYyLTBhNDQxYWM0MjIxYSIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.WjakhZej768pgBc0NNLtt9M12oM-Ch1V8DHVyxbN4yw
